language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
 - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake -qt=qt5 QmakeWatcherConsole.pro
  - make --silent
  - ./QmakeWatcherConsole
  # Desktop
  - qmake -qt=qt5 QmakeWatcherDesktop.pro
  - make --silent
  - ./QmakeWatcherDesktop &
  - sleep 10
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
